"""
Static metadata attributes for Hyundai vehicles.

This module contains all the non-functional metadata for Hyundai vehicles,
including model information, parts, and other documentation-related information.
Footnotes have been moved to footnotes.py and helper functions to base/model_helpers.py.
"""

from typing import Dict, Any
from opendbc.metadata.base.parts_definitions import Harness, Tool, Kit
from opendbc.car.common.conversions import Conversions as CV

# ===== MODEL DATA =====

MODEL_DATA = {
    "Hyundai Azera 2022": {
        "make": "Hyundai",
        "model": "Azera",
        "years": [2022],
        "platform": "HYUNDAI_AZERA_6TH_GEN",
        "package": "All",
        "explicit_parts": [Harness.HYUNDAI_K],
        "explicit_footnotes": [],
        "support_type": "upstream",
        "video_link": None,
        "min_steer_speed": 0.0,
        "min_enable_speed": 0.0,
        "auto_resume": True,
        "visible_in_docs": True
    },
    "Hyundai Azera Hybrid 2019": {
        "make": "Hyundai",
        "model": "Azera Hybrid",
        "years": [2019],
        "platform": "HYUNDAI_AZERA_HEV_6TH_GEN",
        "package": "All",
        "explicit_parts": [Harness.HYUNDAI_C],
        "explicit_footnotes": [],
        "support_type": "upstream",
        "video_link": None,
        "min_steer_speed": 0.0,
        "min_enable_speed": 0.0,
        "auto_resume": True,
        "visible_in_docs": True
    },
    "Hyundai Azera Hybrid 2020": {
        "make": "Hyundai",
        "model": "Azera Hybrid",
        "years": [2020],
        "platform": "HYUNDAI_AZERA_HEV_6TH_GEN",
        "package": "All",
        "explicit_parts": [Harness.HYUNDAI_K],
        "explicit_footnotes": [],
        "support_type": "upstream",
        "video_link": None,
        "min_steer_speed": 0.0,
        "min_enable_speed": 0.0,
        "auto_resume": True,
        "visible_in_docs": True
    },
    "Hyundai Custin 2023": {
        "make": "Hyundai",
        "model": "Custin",
        "years": [2023],
        "platform": "HYUNDAI_CUSTIN_1ST_GEN",
        "package": "All",
        "explicit_parts": [Harness.HYUNDAI_K],
        "explicit_footnotes": [],
        "support_type": "upstream",
        "video_link": None,
        "min_steer_speed": 0.0,
        "min_enable_speed": 0.0,
        "auto_resume": True,
        "visible_in_docs": True
    },
    "Hyundai Elantra 2017-18": {
        "make": "Hyundai",
        "model": "Elantra",
        "years": [2017, 2018],
        "platform": "HYUNDAI_ELANTRA",
        "package": "Smart Cruise Control (SCC)",
        "explicit_parts": [Harness.HYUNDAI_B],
        "explicit_footnotes": ['scc', 'min_speed'],
        "support_type": "upstream",
        "video_link": None,
        "min_steer_speed": 14.30528,
        "min_enable_speed": 19.0 * CV.MPH_TO_MS,
        "auto_resume": True,
        "visible_in_docs": True
    },
    "Hyundai Elantra 2019": {
        "make": "Hyundai",
        "model": "Elantra",
        "years": [2019],
        "platform": "HYUNDAI_ELANTRA",
        "package": "Smart Cruise Control (SCC)",
        "explicit_parts": [Harness.HYUNDAI_G],
        "explicit_footnotes": ['scc', 'min_speed'],
        "support_type": "upstream",
        "video_link": None,
        "min_steer_speed": 14.30528,
        "min_enable_speed": 19.0 * CV.MPH_TO_MS,
        "auto_resume": True,
        "visible_in_docs": True
    },
    "Hyundai Elantra 2021-23": {
        "make": "Hyundai",
        "model": "Elantra",
        "years": [2021, 2022, 2023],
        "platform": "HYUNDAI_ELANTRA_2021",
        "package": "Smart Cruise Control (SCC)",
        "explicit_parts": [Harness.HYUNDAI_K],
        "explicit_footnotes": ['scc'],
        "support_type": "upstream",
        "video_link": "https://youtu.be/_EdYQtV52-c",
        "min_steer_speed": 0.0,
        "min_enable_speed": 0.0,
        "auto_resume": True,
        "visible_in_docs": True
    },
    "Hyundai Elantra GT 2017-20": {
        "make": "Hyundai",
        "model": "Elantra GT",
        "years": [2017, 2018, 2019, 2020],
        "platform": "HYUNDAI_ELANTRA_GT_I30",
        "package": "Smart Cruise Control (SCC)",
        "explicit_parts": [Harness.HYUNDAI_E],
        "explicit_footnotes": ['scc', 'min_speed'],
        "support_type": "upstream",
        "video_link": None,
        "min_steer_speed": 14.30528,
        "min_enable_speed": 0.0,
        "auto_resume": True,
        "visible_in_docs": True
    },
    "Hyundai Elantra Hybrid 2021-23": {
        "make": "Hyundai",
        "model": "Elantra Hybrid",
        "years": [2021, 2022, 2023],
        "platform": "HYUNDAI_ELANTRA_HEV_2021",
        "package": "Smart Cruise Control (SCC)",
        "explicit_parts": [Harness.HYUNDAI_K],
        "explicit_footnotes": ['scc'],
        "support_type": "upstream",
        "video_link": "https://youtu.be/_EdYQtV52-c",
        "min_steer_speed": 0.0,
        "min_enable_speed": 0.0,
        "auto_resume": True,
        "visible_in_docs": True
    },
    "Hyundai Genesis 2015-16": {
        "make": "Hyundai",
        "model": "Genesis",
        "years": [2015, 2016],
        "platform": "HYUNDAI_GENESIS",
        "package": "Smart Cruise Control (SCC)",
        "explicit_parts": [Harness.HYUNDAI_J],
        "explicit_footnotes": ['scc'],
        "support_type": "upstream",
        "video_link": None,
        "min_steer_speed": 0.0,
        "min_enable_speed": 19.0 * CV.MPH_TO_MS,
        "auto_resume": True,
        "visible_in_docs": True
    },
    "Hyundai Ioniq 5 (Southeast Asia and Europe only) 2022-24": {
        "make": "Hyundai",
        "model": "Ioniq 5 (Southeast Asia and Europe only)",
        "years": [2022, 2023, 2024],
        "platform": "HYUNDAI_IONIQ_5",
        "package": "All",
        "explicit_parts": [Harness.HYUNDAI_Q, Kit.CANFD_KIT],
        "explicit_footnotes": [],
        "support_type": "upstream",
        "video_link": None,
        "min_steer_speed": 0.0,
        "min_enable_speed": 0.0,
        "auto_resume": True,
        "visible_in_docs": True
    },
    "Hyundai Ioniq 5 (with HDA II) 2022-24": {
        "make": "Hyundai",
        "model": "Ioniq 5 (with HDA II)",
        "years": [2022, 2023, 2024],
        "platform": "HYUNDAI_IONIQ_5",
        "package": "Highway Driving Assist II",
        "explicit_parts": [Harness.HYUNDAI_Q, Kit.CANFD_KIT],
        "explicit_footnotes": ['scc'],
        "support_type": "upstream",
        "video_link": None,
        "min_steer_speed": 0.0,
        "min_enable_speed": 0.0,
        "auto_resume": True,
        "visible_in_docs": True
    },
    "Hyundai Ioniq 5 (without HDA II) 2022-24": {
        "make": "Hyundai",
        "model": "Ioniq 5 (without HDA II)",
        "years": [2022, 2023, 2024],
        "platform": "HYUNDAI_IONIQ_5",
        "package": "Highway Driving Assist",
        "explicit_parts": [Harness.HYUNDAI_K, Kit.CANFD_KIT],
        "explicit_footnotes": ['scc'],
        "support_type": "upstream",
        "video_link": None,
        "min_steer_speed": 0.0,
        "min_enable_speed": 0.0,
        "auto_resume": True,
        "visible_in_docs": True
    },
    "Hyundai Ioniq 6 (with HDA II) 2023-24": {
        "make": "Hyundai",
        "model": "Ioniq 6 (with HDA II)",
        "years": [2023, 2024],
        "platform": "HYUNDAI_IONIQ_6",
        "package": "Highway Driving Assist II",
        "explicit_parts": [Harness.HYUNDAI_P, Kit.CANFD_KIT],
        "explicit_footnotes": ['scc'],
        "support_type": "upstream",
        "video_link": None,
        "min_steer_speed": 0.0,
        "min_enable_speed": 0.0,
        "auto_resume": True,
        "visible_in_docs": True
    },
    "Hyundai Ioniq Electric 2019": {
        "make": "Hyundai",
        "model": "Ioniq Electric",
        "years": [2019],
        "platform": "HYUNDAI_IONIQ_EV_LTD",
        "package": "Smart Cruise Control (SCC)",
        "explicit_parts": [Harness.HYUNDAI_C],
        "explicit_footnotes": ['scc', 'min_speed'],
        "support_type": "upstream",
        "video_link": None,
        "min_steer_speed": 14.30528,
        "min_enable_speed": 0.0,
        "auto_resume": True,
        "visible_in_docs": True
    },
    "Hyundai Ioniq Electric 2020": {
        "make": "Hyundai",
        "model": "Ioniq Electric",
        "years": [2020],
        "platform": "HYUNDAI_IONIQ_EV_2020",
        "package": "All",
        "explicit_parts": [Harness.HYUNDAI_H],
        "explicit_footnotes": [],
        "support_type": "upstream",
        "video_link": None,
        "min_steer_speed": 0.0,
        "min_enable_speed": 0.0,
        "auto_resume": True,
        "visible_in_docs": True
    },
    "Hyundai Ioniq Hybrid 2017-19": {
        "make": "Hyundai",
        "model": "Ioniq Hybrid",
        "years": [2017, 2018, 2019],
        "platform": "HYUNDAI_IONIQ",
        "package": "Smart Cruise Control (SCC)",
        "explicit_parts": [Harness.HYUNDAI_C],
        "explicit_footnotes": ['scc', 'min_speed'],
        "support_type": "upstream",
        "video_link": None,
        "min_steer_speed": 14.30528,
        "min_enable_speed": 0.0,
        "auto_resume": True,
        "visible_in_docs": True
    },
    "Hyundai Ioniq Hybrid 2020-22": {
        "make": "Hyundai",
        "model": "Ioniq Hybrid",
        "years": [2020, 2021, 2022],
        "platform": "HYUNDAI_IONIQ_HEV_2022",
        "package": "Smart Cruise Control (SCC)",
        "explicit_parts": [Harness.HYUNDAI_H],
        "explicit_footnotes": ['scc'],
        "support_type": "upstream",
        "video_link": None,
        "min_steer_speed": 0.0,
        "min_enable_speed": 0.0,
        "auto_resume": True,
        "visible_in_docs": True
    },
    "Hyundai Ioniq Plug-in Hybrid 2019": {
        "make": "Hyundai",
        "model": "Ioniq Plug-in Hybrid",
        "years": [2019],
        "platform": "HYUNDAI_IONIQ_PHEV_2019",
        "package": "Smart Cruise Control (SCC)",
        "explicit_parts": [Harness.HYUNDAI_C],
        "explicit_footnotes": ['scc', 'min_speed'],
        "support_type": "upstream",
        "video_link": None,
        "min_steer_speed": 14.30528,
        "min_enable_speed": 0.0,
        "auto_resume": True,
        "visible_in_docs": True
    },
    "Hyundai Ioniq Plug-in Hybrid 2020-22": {
        "make": "Hyundai",
        "model": "Ioniq Plug-in Hybrid",
        "years": [2020, 2021, 2022],
        "platform": "HYUNDAI_IONIQ_PHEV",
        "package": "All",
        "explicit_parts": [Harness.HYUNDAI_H],
        "explicit_footnotes": [],
        "support_type": "upstream",
        "video_link": None,
        "min_steer_speed": 0.0,
        "min_enable_speed": 0.0,
        "auto_resume": True,
        "visible_in_docs": True
    },
    "Hyundai Kona 2020": {
        "make": "Hyundai",
        "model": "Kona",
        "years": [2020],
        "platform": "HYUNDAI_KONA",
        "package": "Smart Cruise Control (SCC)",
        "explicit_parts": [Harness.HYUNDAI_B],
        "explicit_footnotes": ['scc'],
        "support_type": "upstream",
        "video_link": None,
        "min_steer_speed": 0.0,
        "min_enable_speed": 2.68224,
        "auto_resume": True,
        "visible_in_docs": True
    },
    "Hyundai Kona 2022": {
        "make": "Hyundai",
        "model": "Kona",
        "years": [2022],
        "platform": "HYUNDAI_KONA_2022",
        "package": "Smart Cruise Control (SCC)",
        "explicit_parts": [Harness.HYUNDAI_O],
        "explicit_footnotes": ['scc'],
        "support_type": "upstream",
        "video_link": None,
        "min_steer_speed": 0.0,
        "min_enable_speed": 0.0,
        "auto_resume": True,
        "visible_in_docs": True
    },
    "Hyundai Kona Electric 2018-21": {
        "make": "Hyundai",
        "model": "Kona Electric",
        "years": [2018, 2019, 2020, 2021],
        "platform": "HYUNDAI_KONA_EV",
        "package": "Smart Cruise Control (SCC)",
        "explicit_parts": [Harness.HYUNDAI_G],
        "explicit_footnotes": ['scc'],
        "support_type": "upstream",
        "video_link": None,
        "min_steer_speed": 0.0,
        "min_enable_speed": 0.0,
        "auto_resume": True,
        "visible_in_docs": True
    },
    "Hyundai Kona Electric 2022-23": {
        "make": "Hyundai",
        "model": "Kona Electric",
        "years": [2022, 2023],
        "platform": "HYUNDAI_KONA_EV_2022",
        "package": "Smart Cruise Control (SCC)",
        "explicit_parts": [Harness.HYUNDAI_O],
        "explicit_footnotes": ['scc'],
        "support_type": "upstream",
        "video_link": None,
        "min_steer_speed": 0.0,
        "min_enable_speed": 0.0,
        "auto_resume": True,
        "visible_in_docs": True
    },
    "Hyundai Kona Electric (with HDA II, Korea only) 2023": {
        "make": "Hyundai",
        "model": "Kona Electric (with HDA II, Korea only)",
        "years": [2023],
        "platform": "HYUNDAI_KONA_EV_2ND_GEN",
        "package": "Smart Cruise Control (SCC)",
        "explicit_parts": [Harness.HYUNDAI_R, Kit.CANFD_KIT],
        "explicit_footnotes": ['scc'],
        "support_type": "upstream",
        "video_link": "https://www.youtube.com/watch?v=U2fOCmcQ8hw",
        "min_steer_speed": 0.0,
        "min_enable_speed": 0.0,
        "auto_resume": True,
        "visible_in_docs": True
    },
    "Hyundai Kona Hybrid 2020": {
        "make": "Hyundai",
        "model": "Kona Hybrid",
        "years": [2020],
        "platform": "HYUNDAI_KONA_HEV",
        "package": "Smart Cruise Control (SCC)",
        "explicit_parts": [Harness.HYUNDAI_I],
        "explicit_footnotes": ['scc'],
        "support_type": "upstream",
        "video_link": None,
        "min_steer_speed": 0.0,
        "min_enable_speed": 0.0,
        "auto_resume": True,
        "visible_in_docs": True
    },
    "Hyundai Nexo 2021": {
        "make": "Hyundai",
        "model": "Nexo",
        "years": [2021],
        "platform": "HYUNDAI_NEXO_1ST_GEN",
        "package": "All",
        "explicit_parts": [Harness.HYUNDAI_H],
        "explicit_footnotes": [],
        "support_type": "upstream",
        "video_link": None,
        "min_steer_speed": 0.0,
        "min_enable_speed": 0.0,
        "auto_resume": True,
        "visible_in_docs": True
    },
    "Hyundai Palisade 2020-22": {
        "make": "Hyundai",
        "model": "Palisade",
        "years": [2020, 2021, 2022],
        "platform": "HYUNDAI_PALISADE",
        "package": "All",
        "explicit_parts": [Harness.HYUNDAI_H],
        "explicit_footnotes": [],
        "support_type": "upstream",
        "video_link": "https://youtu.be/TAnDqjF4fDY?t=456",
        "min_steer_speed": 0.0,
        "min_enable_speed": 0.0,
        "auto_resume": True,
        "visible_in_docs": True
    },
    "Hyundai Santa Cruz 2022-24": {
        "make": "Hyundai",
        "model": "Santa Cruz",
        "years": [2022, 2023, 2024],
        "platform": "HYUNDAI_SANTA_CRUZ_1ST_GEN",
        "package": "Smart Cruise Control (SCC)",
        "explicit_parts": [Harness.HYUNDAI_N, Kit.CANFD_KIT],
        "explicit_footnotes": ['scc'],
        "support_type": "upstream",
        "video_link": None,
        "min_steer_speed": 0.0,
        "min_enable_speed": 0.0,
        "auto_resume": True,
        "visible_in_docs": True
    },
    "Hyundai Santa Fe 2019-20": {
        "make": "Hyundai",
        "model": "Santa Fe",
        "years": [2019, 2020],
        "platform": "HYUNDAI_SANTA_FE",
        "package": "All",
        "explicit_parts": [Harness.HYUNDAI_D],
        "explicit_footnotes": [],
        "support_type": "upstream",
        "video_link": "https://youtu.be/bjDR0YjM__s",
        "min_steer_speed": 0.0,
        "min_enable_speed": 0.0,
        "auto_resume": True,
        "visible_in_docs": True
    },
    "Hyundai Santa Fe 2021-23": {
        "make": "Hyundai",
        "model": "Santa Fe",
        "years": [2021, 2022, 2023],
        "platform": "HYUNDAI_SANTA_FE_2022",
        "package": "All",
        "explicit_parts": [Harness.HYUNDAI_L],
        "explicit_footnotes": [],
        "support_type": "upstream",
        "video_link": "https://youtu.be/VnHzSTygTS4",
        "min_steer_speed": 0.0,
        "min_enable_speed": 0.0,
        "auto_resume": True,
        "visible_in_docs": True
    },
    "Hyundai Santa Fe Hybrid 2022-23": {
        "make": "Hyundai",
        "model": "Santa Fe Hybrid",
        "years": [2022, 2023],
        "platform": "HYUNDAI_SANTA_FE_HEV_2022",
        "package": "All",
        "explicit_parts": [Harness.HYUNDAI_L],
        "explicit_footnotes": [],
        "support_type": "upstream",
        "video_link": None,
        "min_steer_speed": 0.0,
        "min_enable_speed": 0.0,
        "auto_resume": True,
        "visible_in_docs": True
    },
    "Hyundai Santa Fe Plug-in Hybrid 2022-23": {
        "make": "Hyundai",
        "model": "Santa Fe Plug-in Hybrid",
        "years": [2022, 2023],
        "platform": "HYUNDAI_SANTA_FE_PHEV_2022",
        "package": "All",
        "explicit_parts": [Harness.HYUNDAI_L],
        "explicit_footnotes": [],
        "support_type": "upstream",
        "video_link": None,
        "min_steer_speed": 0.0,
        "min_enable_speed": 0.0,
        "auto_resume": True,
        "visible_in_docs": True
    },
    "Hyundai Sonata 2020-23": {
        "make": "Hyundai",
        "model": "Sonata",
        "years": [2020, 2021, 2022, 2023],
        "platform": "HYUNDAI_SONATA",
        "package": "All",
        "explicit_parts": [Harness.HYUNDAI_A],
        "explicit_footnotes": [],
        "support_type": "upstream",
        "video_link": "https://www.youtube.com/watch?v=ix63r9kE3Fw",
        "min_steer_speed": 0.0,
        "min_enable_speed": 0.0,
        "auto_resume": True,
        "visible_in_docs": True
    },
    "Hyundai Sonata 2018-19": {
        "make": "Hyundai",
        "model": "Sonata",
        "years": [2018, 2019],
        "platform": "HYUNDAI_SONATA_LF",
        "package": "Smart Cruise Control (SCC)",
        "explicit_parts": [Harness.HYUNDAI_E],
        "explicit_footnotes": ['scc'],
        "support_type": "upstream",
        "video_link": None,
        "min_steer_speed": 0.0,
        "min_enable_speed": 0.0,
        "auto_resume": True,
        "visible_in_docs": True
    },
    "Hyundai Sonata Hybrid 2020-23": {
        "make": "Hyundai",
        "model": "Sonata Hybrid",
        "years": [2020, 2021, 2022, 2023],
        "platform": "HYUNDAI_SONATA_HYBRID",
        "package": "All",
        "explicit_parts": [Harness.HYUNDAI_A],
        "explicit_footnotes": [],
        "support_type": "upstream",
        "video_link": None,
        "min_steer_speed": 0.0,
        "min_enable_speed": 0.0,
        "auto_resume": True,
        "visible_in_docs": True
    },
    "Hyundai Staria 2023": {
        "make": "Hyundai",
        "model": "Staria",
        "years": [2023],
        "platform": "HYUNDAI_STARIA_4TH_GEN",
        "package": "All",
        "explicit_parts": [Harness.HYUNDAI_K, Kit.CANFD_KIT],
        "explicit_footnotes": [],
        "support_type": "upstream",
        "video_link": None,
        "min_steer_speed": 0.0,
        "min_enable_speed": 0.0,
        "auto_resume": True,
        "visible_in_docs": True
    },
    "Hyundai Tucson 2021": {
        "make": "Hyundai",
        "model": "Tucson",
        "years": [2021],
        "platform": "HYUNDAI_TUCSON",
        "package": "Smart Cruise Control (SCC)",
        "explicit_parts": [Harness.HYUNDAI_L],
        "explicit_footnotes": ['scc'],
        "support_type": "upstream",
        "video_link": None,
        "min_steer_speed": 0.0,
        "min_enable_speed": 19.0 * CV.MPH_TO_MS,
        "auto_resume": True,
        "visible_in_docs": True
    },
    "Hyundai Tucson 2022": {
        "make": "Hyundai",
        "model": "Tucson",
        "years": [2022],
        "platform": "HYUNDAI_TUCSON_4TH_GEN",
        "package": "Smart Cruise Control (SCC)",
        "explicit_parts": [Harness.HYUNDAI_N, Kit.CANFD_KIT],
        "explicit_footnotes": ['scc'],
        "support_type": "upstream",
        "video_link": None,
        "min_steer_speed": 0.0,
        "min_enable_speed": 0.0,
        "auto_resume": True,
        "visible_in_docs": True
    },
    "Hyundai Tucson 2023-24": {
        "make": "Hyundai",
        "model": "Tucson",
        "years": [2023, 2024],
        "platform": "HYUNDAI_TUCSON_4TH_GEN",
        "package": "All",
        "explicit_parts": [Harness.HYUNDAI_N, Kit.CANFD_KIT],
        "explicit_footnotes": [],
        "support_type": "upstream",
        "video_link": None,
        "min_steer_speed": 0.0,
        "min_enable_speed": 0.0,
        "auto_resume": True,
        "visible_in_docs": True
    },
    "Hyundai Tucson Diesel 2019": {
        "make": "Hyundai",
        "model": "Tucson Diesel",
        "years": [2019],
        "platform": "HYUNDAI_TUCSON",
        "package": "Smart Cruise Control (SCC)",
        "explicit_parts": [Harness.HYUNDAI_L],
        "explicit_footnotes": ['scc'],
        "support_type": "upstream",
        "video_link": None,
        "min_steer_speed": 0.0,
        "min_enable_speed": 0.0,
        "auto_resume": True,
        "visible_in_docs": True
    },
    "Hyundai Tucson Hybrid 2022-24": {
        "make": "Hyundai",
        "model": "Tucson Hybrid",
        "years": [2022, 2023, 2024],
        "platform": "HYUNDAI_TUCSON_4TH_GEN",
        "package": "All",
        "explicit_parts": [Harness.HYUNDAI_N, Kit.CANFD_KIT],
        "explicit_footnotes": [],
        "support_type": "upstream",
        "video_link": None,
        "min_steer_speed": 0.0,
        "min_enable_speed": 0.0,
        "auto_resume": True,
        "visible_in_docs": True
    },
    "Hyundai Tucson Plug-in Hybrid 2024": {
        "make": "Hyundai",
        "model": "Tucson Plug-in Hybrid",
        "years": [2024],
        "platform": "HYUNDAI_TUCSON_4TH_GEN",
        "package": "All",
        "explicit_parts": [Harness.HYUNDAI_N, Kit.CANFD_KIT],
        "explicit_footnotes": [],
        "support_type": "upstream",
        "video_link": None,
        "min_steer_speed": 0.0,
        "min_enable_speed": 0.0,
        "auto_resume": True,
        "visible_in_docs": True
    },
    "Hyundai Veloster 2019-20": {
        "make": "Hyundai",
        "model": "Veloster",
        "years": [2019, 2020],
        "platform": "HYUNDAI_VELOSTER",
        "package": "Smart Cruise Control (SCC)",
        "explicit_parts": [Harness.HYUNDAI_E],
        "explicit_footnotes": ['scc'],
        "support_type": "upstream",
        "video_link": None,
        "min_steer_speed": 0.0,
        "min_enable_speed": 5.0 * CV.MPH_TO_MS,
        "auto_resume": True,
        "visible_in_docs": True
    },
    "Hyundai i30 2017-19": {
        "make": "Hyundai",
        "model": "i30",
        "years": [2017, 2018, 2019],
        "platform": "HYUNDAI_ELANTRA_GT_I30",
        "package": "Smart Cruise Control (SCC)",
        "explicit_parts": [Harness.HYUNDAI_E],
        "explicit_footnotes": ['scc', 'min_speed'],
        "support_type": "upstream",
        "video_link": None,
        "min_steer_speed": 14.30528,
        "min_enable_speed": 0.0,
        "auto_resume": True,
        "visible_in_docs": True
    },
    "Kia Carnival 2022-24": {
        "make": "Kia",
        "model": "Carnival",
        "years": [2022, 2023, 2024],
        "platform": "KIA_CARNIVAL_4TH_GEN",
        "package": "Smart Cruise Control (SCC)",
        "explicit_parts": [Harness.HYUNDAI_A, Kit.CANFD_KIT],
        "explicit_footnotes": ['scc', 'radar_scc'],
        "support_type": "upstream",
        "video_link": None,
        "min_steer_speed": 0.0,
        "min_enable_speed": 0.0,
        "auto_resume": True,
        "visible_in_docs": True
    },
    "Kia Carnival (China only) 2023": {
        "make": "Kia",
        "model": "Carnival (China only)",
        "years": [2023],
        "platform": "KIA_CARNIVAL_4TH_GEN",
        "package": "Smart Cruise Control (SCC)",
        "explicit_parts": [Harness.HYUNDAI_K, Kit.CANFD_KIT],
        "explicit_footnotes": ['scc', 'radar_scc'],
        "support_type": "upstream",
        "video_link": None,
        "min_steer_speed": 0.0,
        "min_enable_speed": 0.0,
        "auto_resume": True,
        "visible_in_docs": True
    },
    "Kia Ceed 2019-21": {
        "make": "Kia",
        "model": "Ceed",
        "years": [2019, 2020, 2021],
        "platform": "KIA_CEED",
        "package": "Smart Cruise Control (SCC)",
        "explicit_parts": [Harness.HYUNDAI_E],
        "explicit_footnotes": ['scc'],
        "support_type": "upstream",
        "video_link": None,
        "min_steer_speed": 0.0,
        "min_enable_speed": 0.0,
        "auto_resume": True,
        "visible_in_docs": True
    },
    "Kia EV6 (Southeast Asia only) 2022-24": {
        "make": "Kia",
        "model": "EV6 (Southeast Asia only)",
        "years": [2022, 2023, 2024],
        "platform": "KIA_EV6",
        "package": "All",
        "explicit_parts": [Harness.HYUNDAI_P, Kit.CANFD_KIT],
        "explicit_footnotes": [],
        "support_type": "upstream",
        "video_link": None,
        "min_steer_speed": 0.0,
        "min_enable_speed": 0.0,
        "auto_resume": True,
        "visible_in_docs": True
    },
    "Kia EV6 (with HDA II) 2022-24": {
        "make": "Kia",
        "model": "EV6 (with HDA II)",
        "years": [2022, 2023, 2024],
        "platform": "KIA_EV6",
        "package": "Highway Driving Assist II",
        "explicit_parts": [Harness.HYUNDAI_P, Kit.CANFD_KIT],
        "explicit_footnotes": ['scc'],
        "support_type": "upstream",
        "video_link": None,
        "min_steer_speed": 0.0,
        "min_enable_speed": 0.0,
        "auto_resume": True,
        "visible_in_docs": True
    },
    "Kia EV6 (without HDA II) 2022-24": {
        "make": "Kia",
        "model": "EV6 (without HDA II)",
        "years": [2022, 2023, 2024],
        "platform": "KIA_EV6",
        "package": "Highway Driving Assist",
        "explicit_parts": [Harness.HYUNDAI_L, Kit.CANFD_KIT],
        "explicit_footnotes": ['scc'],
        "support_type": "upstream",
        "video_link": None,
        "min_steer_speed": 0.0,
        "min_enable_speed": 0.0,
        "auto_resume": True,
        "visible_in_docs": True
    },
    "Kia Forte 2019-21": {
        "make": "Kia",
        "model": "Forte",
        "years": [2019, 2020, 2021],
        "platform": "KIA_FORTE",
        "package": "Smart Cruise Control (SCC)",
        "explicit_parts": [Harness.HYUNDAI_G],
        "explicit_footnotes": ['scc'],
        "support_type": "upstream",
        "video_link": None,
        "min_steer_speed": 0.0,
        "min_enable_speed": 2.68224,
        "auto_resume": True,
        "visible_in_docs": True
    },
    "Kia Forte 2022-23": {
        "make": "Kia",
        "model": "Forte",
        "years": [2022, 2023],
        "platform": "KIA_FORTE",
        "package": "Smart Cruise Control (SCC)",
        "explicit_parts": [Harness.HYUNDAI_E],
        "explicit_footnotes": ['scc'],
        "support_type": "upstream",
        "video_link": None,
        "min_steer_speed": 0.0,
        "min_enable_speed": 0.0,
        "auto_resume": True,
        "visible_in_docs": True
    },
    "Kia K5 2021-24": {
        "make": "Kia",
        "model": "K5",
        "years": [2021, 2022, 2023, 2024],
        "platform": "KIA_K5_2021",
        "package": "Smart Cruise Control (SCC)",
        "explicit_parts": [Harness.HYUNDAI_A],
        "explicit_footnotes": ['scc'],
        "support_type": "upstream",
        "video_link": None,
        "min_steer_speed": 0.0,
        "min_enable_speed": 0.0,
        "auto_resume": True,
        "visible_in_docs": True
    },
    "Kia K5 Hybrid 2020-22": {
        "make": "Kia",
        "model": "K5 Hybrid",
        "years": [2020, 2021, 2022],
        "platform": "KIA_K5_HEV_2020",
        "package": "Smart Cruise Control (SCC)",
        "explicit_parts": [Harness.HYUNDAI_A],
        "explicit_footnotes": ['scc'],
        "support_type": "upstream",
        "video_link": None,
        "min_steer_speed": 0.0,
        "min_enable_speed": 0.0,
        "auto_resume": True,
        "visible_in_docs": True
    },
    "Kia K8 Hybrid (with HDA II) 2023": {
        "make": "Kia",
        "model": "K8 Hybrid (with HDA II)",
        "years": [2023],
        "platform": "KIA_K8_HEV_1ST_GEN",
        "package": "Highway Driving Assist II",
        "explicit_parts": [Harness.HYUNDAI_Q, Kit.CANFD_KIT],
        "explicit_footnotes": ['scc'],
        "support_type": "upstream",
        "video_link": None,
        "min_steer_speed": 0.0,
        "min_enable_speed": 0.0,
        "auto_resume": True,
        "visible_in_docs": True
    },
    "Kia Niro EV 2019": {
        "make": "Kia",
        "model": "Niro EV",
        "years": [2019],
        "platform": "KIA_NIRO_EV",
        "package": "All",
        "explicit_parts": [Harness.HYUNDAI_H],
        "explicit_footnotes": [],
        "support_type": "upstream",
        "video_link": "https://www.youtube.com/watch?v=lT7zcG6ZpGo",
        "min_steer_speed": 0.0,
        "min_enable_speed": 0.0,
        "auto_resume": True,
        "visible_in_docs": True
    },
    "Kia Niro EV 2020": {
        "make": "Kia",
        "model": "Niro EV",
        "years": [2020],
        "platform": "KIA_NIRO_EV",
        "package": "All",
        "explicit_parts": [Harness.HYUNDAI_F],
        "explicit_footnotes": [],
        "support_type": "upstream",
        "video_link": "https://www.youtube.com/watch?v=lT7zcG6ZpGo",
        "min_steer_speed": 0.0,
        "min_enable_speed": 0.0,
        "auto_resume": True,
        "visible_in_docs": True
    },
    "Kia Niro EV 2021": {
        "make": "Kia",
        "model": "Niro EV",
        "years": [2021],
        "platform": "KIA_NIRO_EV",
        "package": "All",
        "explicit_parts": [Harness.HYUNDAI_C],
        "explicit_footnotes": [],
        "support_type": "upstream",
        "video_link": "https://www.youtube.com/watch?v=lT7zcG6ZpGo",
        "min_steer_speed": 0.0,
        "min_enable_speed": 0.0,
        "auto_resume": True,
        "visible_in_docs": True
    },
    "Kia Niro EV 2022": {
        "make": "Kia",
        "model": "Niro EV",
        "years": [2022],
        "platform": "KIA_NIRO_EV",
        "package": "All",
        "explicit_parts": [Harness.HYUNDAI_H],
        "explicit_footnotes": [],
        "support_type": "upstream",
        "video_link": "https://www.youtube.com/watch?v=lT7zcG6ZpGo",
        "min_steer_speed": 0.0,
        "min_enable_speed": 0.0,
        "auto_resume": True,
        "visible_in_docs": True
    },
    "Kia Niro EV 2023": {
        "make": "Kia",
        "model": "Niro EV",
        "years": [2023],
        "platform": "KIA_NIRO_EV_2ND_GEN",
        "package": "All",
        "explicit_parts": [Harness.HYUNDAI_A, Kit.CANFD_KIT],
        "explicit_footnotes": [],
        "support_type": "upstream",
        "video_link": None,
        "min_steer_speed": 0.0,
        "min_enable_speed": 0.0,
        "auto_resume": True,
        "visible_in_docs": True
    },
    "Kia Niro Hybrid 2018": {
        "make": "Kia",
        "model": "Niro Hybrid",
        "years": [2018],
        "platform": "KIA_NIRO_PHEV",
        "package": "All",
        "explicit_parts": [Harness.HYUNDAI_C],
        "explicit_footnotes": ['min_speed'],
        "support_type": "upstream",
        "video_link": None,
        "min_steer_speed": 14.30528,
        "min_enable_speed": 4.470400000000001,
        "auto_resume": True,
        "visible_in_docs": True
    },
    "Kia Niro Hybrid 2021": {
        "make": "Kia",
        "model": "Niro Hybrid",
        "years": [2021],
        "platform": "KIA_NIRO_HEV_2021",
        "package": "Smart Cruise Control (SCC)",
        "explicit_parts": [Harness.HYUNDAI_D],
        "explicit_footnotes": ['scc'],
        "support_type": "upstream",
        "video_link": None,
        "min_steer_speed": 0.0,
        "min_enable_speed": 0.0,
        "auto_resume": True,
        "visible_in_docs": True
    },
    "Kia Niro Hybrid 2022": {
        "make": "Kia",
        "model": "Niro Hybrid",
        "years": [2022],
        "platform": "KIA_NIRO_HEV_2021",
        "package": "Smart Cruise Control (SCC)",
        "explicit_parts": [Harness.HYUNDAI_F],
        "explicit_footnotes": ['scc'],
        "support_type": "upstream",
        "video_link": None,
        "min_steer_speed": 0.0,
        "min_enable_speed": 0.0,
        "auto_resume": True,
        "visible_in_docs": True
    },
    "Kia Niro Hybrid 2023": {
        "make": "Kia",
        "model": "Niro Hybrid",
        "years": [2023],
        "platform": "KIA_NIRO_HEV_2ND_GEN",
        "package": "Smart Cruise Control (SCC)",
        "explicit_parts": [Harness.HYUNDAI_A, Kit.CANFD_KIT],
        "explicit_footnotes": ['scc'],
        "support_type": "upstream",
        "video_link": None,
        "min_steer_speed": 0.0,
        "min_enable_speed": 0.0,
        "auto_resume": True,
        "visible_in_docs": True
    },
    "Kia Niro Plug-in Hybrid 2018-19": {
        "make": "Kia",
        "model": "Niro Plug-in Hybrid",
        "years": [2018, 2019],
        "platform": "KIA_NIRO_PHEV",
        "package": "All",
        "explicit_parts": [Harness.HYUNDAI_C],
        "explicit_footnotes": ['min_speed'],
        "support_type": "upstream",
        "video_link": None,
        "min_steer_speed": 14.30528,
        "min_enable_speed": 4.470400000000001,
        "auto_resume": True,
        "visible_in_docs": True
    },
    "Kia Niro Plug-in Hybrid 2020": {
        "make": "Kia",
        "model": "Niro Plug-in Hybrid",
        "years": [2020],
        "platform": "KIA_NIRO_PHEV",
        "package": "Smart Cruise Control (SCC)",
        "explicit_parts": [Harness.HYUNDAI_D],
        "explicit_footnotes": ['scc', 'min_speed'],
        "support_type": "upstream",
        "video_link": None,
        "min_steer_speed": 14.30528,
        "min_enable_speed": 0.0,
        "auto_resume": True,
        "visible_in_docs": True
    },
    "Kia Niro Plug-in Hybrid 2021": {
        "make": "Kia",
        "model": "Niro Plug-in Hybrid",
        "years": [2021],
        "platform": "KIA_NIRO_PHEV_2022",
        "package": "Smart Cruise Control (SCC)",
        "explicit_parts": [Harness.HYUNDAI_D],
        "explicit_footnotes": ['scc'],
        "support_type": "upstream",
        "video_link": None,
        "min_steer_speed": 0.0,
        "min_enable_speed": 0.0,
        "auto_resume": True,
        "visible_in_docs": True
    },
    "Kia Niro Plug-in Hybrid 2022": {
        "make": "Kia",
        "model": "Niro Plug-in Hybrid",
        "years": [2022],
        "platform": "KIA_NIRO_PHEV_2022",
        "package": "Smart Cruise Control (SCC)",
        "explicit_parts": [Harness.HYUNDAI_F],
        "explicit_footnotes": ['scc'],
        "support_type": "upstream",
        "video_link": None,
        "min_steer_speed": 0.0,
        "min_enable_speed": 0.0,
        "auto_resume": True,
        "visible_in_docs": True
    },
    "Kia Optima 2017": {
        "make": "Kia",
        "model": "Optima",
        "years": [2017],
        "platform": "KIA_OPTIMA_G4",
        "package": "Advanced Smart Cruise Control",
        "explicit_parts": [Harness.HYUNDAI_B],
        "explicit_footnotes": ['scc', 'min_speed'],
        "support_type": "upstream",
        "video_link": None,
        "min_steer_speed": 14.30528,
        "min_enable_speed": 0.0,
        "auto_resume": True,
        "visible_in_docs": True
    },
    "Kia Optima 2019-20": {
        "make": "Kia",
        "model": "Optima",
        "years": [2019, 2020],
        "platform": "KIA_OPTIMA_G4_FL",
        "package": "Smart Cruise Control (SCC)",
        "explicit_parts": [Harness.HYUNDAI_G],
        "explicit_footnotes": ['scc'],
        "support_type": "upstream",
        "video_link": None,
        "min_steer_speed": 0.0,
        "min_enable_speed": 0.0,
        "auto_resume": True,
        "visible_in_docs": True
    },
    "Kia Optima Hybrid 2017": {
        "make": "Kia",
        "model": "Optima Hybrid",
        "years": [2017],
        "platform": "KIA_OPTIMA_H",
        "package": "Advanced Smart Cruise Control",
        "explicit_parts": [Harness.HYUNDAI_C],
        "explicit_footnotes": ['scc'],
        "support_type": "upstream",
        "video_link": None,
        "min_steer_speed": 0.0,
        "min_enable_speed": 0.0,
        "auto_resume": True,
        "visible_in_docs": True
    },
    "Kia Optima Hybrid 2019": {
        "make": "Kia",
        "model": "Optima Hybrid",
        "years": [2019],
        "platform": "KIA_OPTIMA_H_G4_FL",
        "package": "Smart Cruise Control (SCC)",
        "explicit_parts": [Harness.HYUNDAI_H],
        "explicit_footnotes": ['scc'],
        "support_type": "upstream",
        "video_link": None,
        "min_steer_speed": 0.0,
        "min_enable_speed": 0.0,
        "auto_resume": True,
        "visible_in_docs": True
    },
    "Kia Seltos 2021": {
        "make": "Kia",
        "model": "Seltos",
        "years": [2021],
        "platform": "KIA_SELTOS",
        "package": "Smart Cruise Control (SCC)",
        "explicit_parts": [Harness.HYUNDAI_A],
        "explicit_footnotes": ['scc'],
        "support_type": "upstream",
        "video_link": None,
        "min_steer_speed": 0.0,
        "min_enable_speed": 0.0,
        "auto_resume": True,
        "visible_in_docs": True
    },
    "Kia Sorento 2018": {
        "make": "Kia",
        "model": "Sorento",
        "years": [2018],
        "platform": "KIA_SORENTO",
        "package": "Advanced Smart Cruise Control & LKAS",
        "explicit_parts": [Harness.HYUNDAI_E],
        "explicit_footnotes": ['scc'],
        "support_type": "upstream",
        "video_link": "https://www.youtube.com/watch?v=Fkh3s6WHJz8",
        "min_steer_speed": 0.0,
        "min_enable_speed": 0.0,
        "auto_resume": True,
        "visible_in_docs": True
    },
    "Kia Sorento 2019": {
        "make": "Kia",
        "model": "Sorento",
        "years": [2019],
        "platform": "KIA_SORENTO",
        "package": "Smart Cruise Control (SCC)",
        "explicit_parts": [Harness.HYUNDAI_E],
        "explicit_footnotes": ['scc'],
        "support_type": "upstream",
        "video_link": "https://www.youtube.com/watch?v=Fkh3s6WHJz8",
        "min_steer_speed": 0.0,
        "min_enable_speed": 0.0,
        "auto_resume": True,
        "visible_in_docs": True
    },
    "Kia Sorento 2021-23": {
        "make": "Kia",
        "model": "Sorento",
        "years": [2021, 2022, 2023],
        "platform": "KIA_SORENTO_4TH_GEN",
        "package": "Smart Cruise Control (SCC)",
        "explicit_parts": [Harness.HYUNDAI_K, Kit.CANFD_KIT],
        "explicit_footnotes": ['scc', 'radar_scc'],
        "support_type": "upstream",
        "video_link": None,
        "min_steer_speed": 0.0,
        "min_enable_speed": 0.0,
        "auto_resume": True,
        "visible_in_docs": True
    },
    "Kia Sorento Hybrid 2021-23": {
        "make": "Kia",
        "model": "Sorento Hybrid",
        "years": [2021, 2022, 2023],
        "platform": "KIA_SORENTO_HEV_4TH_GEN",
        "package": "All",
        "explicit_parts": [Harness.HYUNDAI_A, Kit.CANFD_KIT],
        "explicit_footnotes": ['radar_scc'],
        "support_type": "upstream",
        "video_link": None,
        "min_steer_speed": 0.0,
        "min_enable_speed": 0.0,
        "auto_resume": True,
        "visible_in_docs": True
    },
    "Kia Sorento Plug-in Hybrid 2022-23": {
        "make": "Kia",
        "model": "Sorento Plug-in Hybrid",
        "years": [2022, 2023],
        "platform": "KIA_SORENTO_HEV_4TH_GEN",
        "package": "All",
        "explicit_parts": [Harness.HYUNDAI_A, Kit.CANFD_KIT],
        "explicit_footnotes": ['radar_scc'],
        "support_type": "upstream",
        "video_link": None,
        "min_steer_speed": 0.0,
        "min_enable_speed": 0.0,
        "auto_resume": True,
        "visible_in_docs": True
    },
    "Kia Sportage 2023-24": {
        "make": "Kia",
        "model": "Sportage",
        "years": [2023, 2024],
        "platform": "KIA_SPORTAGE_5TH_GEN",
        "package": "Smart Cruise Control (SCC)",
        "explicit_parts": [Harness.HYUNDAI_N, Kit.CANFD_KIT],
        "explicit_footnotes": ['scc'],
        "support_type": "upstream",
        "video_link": None,
        "min_steer_speed": 0.0,
        "min_enable_speed": 0.0,
        "auto_resume": True,
        "visible_in_docs": True
    },
    "Kia Sportage Hybrid 2023": {
        "make": "Kia",
        "model": "Sportage Hybrid",
        "years": [2023],
        "platform": "KIA_SPORTAGE_5TH_GEN",
        "package": "Smart Cruise Control (SCC)",
        "explicit_parts": [Harness.HYUNDAI_N, Kit.CANFD_KIT],
        "explicit_footnotes": ['scc'],
        "support_type": "upstream",
        "video_link": None,
        "min_steer_speed": 0.0,
        "min_enable_speed": 0.0,
        "auto_resume": True,
        "visible_in_docs": True
    },
    "Kia Stinger 2018-20": {
        "make": "Kia",
        "model": "Stinger",
        "years": [2018, 2019, 2020],
        "platform": "KIA_STINGER",
        "package": "Smart Cruise Control (SCC)",
        "explicit_parts": [Harness.HYUNDAI_C],
        "explicit_footnotes": ['scc'],
        "support_type": "upstream",
        "video_link": "https://www.youtube.com/watch?v=MJ94qoofYw0",
        "min_steer_speed": 0.0,
        "min_enable_speed": 0.0,
        "auto_resume": True,
        "visible_in_docs": True
    },
    "Kia Stinger 2022-23": {
        "make": "Kia",
        "model": "Stinger",
        "years": [2022, 2023],
        "platform": "KIA_STINGER_2022",
        "package": "All",
        "explicit_parts": [Harness.HYUNDAI_K],
        "explicit_footnotes": [],
        "support_type": "upstream",
        "video_link": None,
        "min_steer_speed": 0.0,
        "min_enable_speed": 0.0,
        "auto_resume": True,
        "visible_in_docs": True
    },
    "Kia Telluride 2020-22": {
        "make": "Kia",
        "model": "Telluride",
        "years": [2020, 2021, 2022],
        "platform": "HYUNDAI_PALISADE",
        "package": "All",
        "explicit_parts": [Harness.HYUNDAI_H],
        "explicit_footnotes": [],
        "support_type": "upstream",
        "video_link": None,
        "min_steer_speed": 0.0,
        "min_enable_speed": 0.0,
        "auto_resume": True,
        "visible_in_docs": True
    },
    "Genesis G70 2018": {
        "make": "Genesis",
        "model": "G70",
        "years": [2018],
        "platform": "GENESIS_G70",
        "package": "All",
        "explicit_parts": [Harness.HYUNDAI_F],
        "explicit_footnotes": [],
        "support_type": "upstream",
        "video_link": None,
        "min_steer_speed": 0.0,
        "min_enable_speed": 0.0,
        "auto_resume": True,
        "visible_in_docs": True
    },
    "Genesis G70 2019-21": {
        "make": "Genesis",
        "model": "G70",
        "years": [2019, 2020, 2021],
        "platform": "GENESIS_G70_2020",
        "package": "All",
        "explicit_parts": [Harness.HYUNDAI_F],
        "explicit_footnotes": [],
        "support_type": "upstream",
        "video_link": None,
        "min_steer_speed": 0.0,
        "min_enable_speed": 0.0,
        "auto_resume": True,
        "visible_in_docs": True
    },
    "Genesis G70 2022-23": {
        "make": "Genesis",
        "model": "G70",
        "years": [2022, 2023],
        "platform": "GENESIS_G70_2020",
        "package": "All",
        "explicit_parts": [Harness.HYUNDAI_L],
        "explicit_footnotes": [],
        "support_type": "upstream",
        "video_link": None,
        "min_steer_speed": 0.0,
        "min_enable_speed": 0.0,
        "auto_resume": True,
        "visible_in_docs": True
    },
    "Genesis G80 2017": {
        "make": "Genesis",
        "model": "G80",
        "years": [2017],
        "platform": "HYUNDAI_GENESIS",
        "package": "All",
        "explicit_parts": [Harness.HYUNDAI_J],
        "explicit_footnotes": [],
        "support_type": "upstream",
        "video_link": None,
        "min_steer_speed": 0.0,
        "min_enable_speed": 19.0 * CV.MPH_TO_MS,
        "auto_resume": True,
        "visible_in_docs": True
    },
    "Genesis G80 2018-19": {
        "make": "Genesis",
        "model": "G80",
        "years": [2018, 2019],
        "platform": "GENESIS_G80",
        "package": "All",
        "explicit_parts": [Harness.HYUNDAI_H],
        "explicit_footnotes": [],
        "support_type": "upstream",
        "video_link": None,
        "min_steer_speed": 0.0,
        "min_enable_speed": 0.0,
        "auto_resume": True,
        "visible_in_docs": True
    },
    "Genesis G80 (2.5T Advanced Trim, with HDA II) 2024": {
        "make": "Genesis",
        "model": "G80 (2.5T Advanced Trim, with HDA II)",
        "years": [2024],
        "platform": "GENESIS_G80_2ND_GEN_FL",
        "package": "Highway Driving Assist II",
        "explicit_parts": [Harness.HYUNDAI_P, Kit.CANFD_KIT],
        "explicit_footnotes": ['scc'],
        "support_type": "upstream",
        "video_link": None,
        "min_steer_speed": 0.0,
        "min_enable_speed": 0.0,
        "auto_resume": True,
        "visible_in_docs": True
    },
    "Genesis G90 2017-20": {
        "make": "Genesis",
        "model": "G90",
        "years": [2017, 2018, 2019, 2020],
        "platform": "GENESIS_G90",
        "package": "All",
        "explicit_parts": [Harness.HYUNDAI_C],
        "explicit_footnotes": [],
        "support_type": "upstream",
        "video_link": None,
        "min_steer_speed": 0.0,
        "min_enable_speed": 0.0,
        "auto_resume": True,
        "visible_in_docs": True
    },
    "Genesis GV60 (Advanced Trim) 2023": {
        "make": "Genesis",
        "model": "GV60 (Advanced Trim)",
        "years": [2023],
        "platform": "GENESIS_GV60_EV_1ST_GEN",
        "package": "All",
        "explicit_parts": [Harness.HYUNDAI_A, Kit.CANFD_KIT],
        "explicit_footnotes": [],
        "support_type": "upstream",
        "video_link": None,
        "min_steer_speed": 0.0,
        "min_enable_speed": 0.0,
        "auto_resume": True,
        "visible_in_docs": True
    },
    "Genesis GV60 (Performance Trim) 2022-23": {
        "make": "Genesis",
        "model": "GV60 (Performance Trim)",
        "years": [2022, 2023],
        "platform": "GENESIS_GV60_EV_1ST_GEN",
        "package": "All",
        "explicit_parts": [Harness.HYUNDAI_K, Kit.CANFD_KIT],
        "explicit_footnotes": [],
        "support_type": "upstream",
        "video_link": None,
        "min_steer_speed": 0.0,
        "min_enable_speed": 0.0,
        "auto_resume": True,
        "visible_in_docs": True
    },
    "Genesis GV70 (2.5T Trim, without HDA II) 2022-24": {
        "make": "Genesis",
        "model": "GV70 (2.5T Trim, without HDA II)",
        "years": [2022, 2023, 2024],
        "platform": "GENESIS_GV70_1ST_GEN",
        "package": "All",
        "explicit_parts": [Harness.HYUNDAI_L, Kit.CANFD_KIT],
        "explicit_footnotes": ['radar_scc'],
        "support_type": "upstream",
        "video_link": None,
        "min_steer_speed": 0.0,
        "min_enable_speed": 0.0,
        "auto_resume": True,
        "visible_in_docs": True
    },
    "Genesis GV70 (3.5T Trim, without HDA II) 2022-23": {
        "make": "Genesis",
        "model": "GV70 (3.5T Trim, without HDA II)",
        "years": [2022, 2023],
        "platform": "GENESIS_GV70_1ST_GEN",
        "package": "All",
        "explicit_parts": [Harness.HYUNDAI_M, Kit.CANFD_KIT],
        "explicit_footnotes": ['radar_scc'],
        "support_type": "upstream",
        "video_link": None,
        "min_steer_speed": 0.0,
        "min_enable_speed": 0.0,
        "auto_resume": True,
        "visible_in_docs": True
    },
    "Genesis GV70 Electrified (Australia Only) 2022": {
        "make": "Genesis",
        "model": "GV70 Electrified (Australia Only)",
        "years": [2022],
        "platform": "GENESIS_GV70_ELECTRIFIED_1ST_GEN",
        "package": "All",
        "explicit_parts": [Harness.HYUNDAI_Q, Kit.CANFD_KIT],
        "explicit_footnotes": [],
        "support_type": "upstream",
        "video_link": None,
        "min_steer_speed": 0.0,
        "min_enable_speed": 0.0,
        "auto_resume": True,
        "visible_in_docs": True
    },
    "Genesis GV70 Electrified (with HDA II) 2023-24": {
        "make": "Genesis",
        "model": "GV70 Electrified (with HDA II)",
        "years": [2023, 2024],
        "platform": "GENESIS_GV70_ELECTRIFIED_1ST_GEN",
        "package": "Highway Driving Assist II",
        "explicit_parts": [Harness.HYUNDAI_Q, Kit.CANFD_KIT],
        "explicit_footnotes": ['scc'],
        "support_type": "upstream",
        "video_link": None,
        "min_steer_speed": 0.0,
        "min_enable_speed": 0.0,
        "auto_resume": True,
        "visible_in_docs": True
    },
    "Genesis GV80 2023": {
        "make": "Genesis",
        "model": "GV80",
        "years": [2023],
        "platform": "GENESIS_GV80",
        "package": "All",
        "explicit_parts": [Harness.HYUNDAI_M, Kit.CANFD_KIT],
        "explicit_footnotes": ['radar_scc'],
        "support_type": "upstream",
        "video_link": None,
        "min_steer_speed": 0.0,
        "min_enable_speed": 0.0,
        "auto_resume": True,
        "visible_in_docs": True
    },
}